### ISSUE TITLE
Changing year or months without pressing arrows

### ISSUE THREAD

**Issue by JodasSenpai** [rwbr/flutter_neat_and_clean_calendar#23]
Hi, thank you for the neat calendar.

Problem: When trying to select date years back or ahead, you need to get to it by one month at the time(by pressing arrows).
Feature request: Be able to get to specific year by either entering it or. by having some list of years to choose from when pressing the current year.

Great job on the library.

**Comment by rwbr** [comment]
Thank you for your suggestion. I will consider a solution to it.

**Comment by rwbr** [comment]
You may check out branch [feature/#23-jump-to-date-button](https://github.com/rwbr/flutter_neat_and_clean_calendar/tree/feature/%2323-jump-to-date-button) and try out the new UI element. Maybe you could give me a quick feedback, if that solution satisfies your feature request.

**Comment by JodasSenpai** [comment]
Hi, thank you for the quick update. 
I think that the jumpDate feature is kind of a miss. It does everything that this library does. Except for the event showing. It is quick solution but I cannot use it in my application. I know it is a lot of work but I think that the when the jumpDate button(or year) is clicked, the showed week/month days should change to years number. Like in the showDatePicker when you click on the year number. 
I am sorry if this sounds "picky" since you already helped me so much with this library and responded so fast. Maybe I could help out if I can.

**Comment by rwbr** [comment]
Hi! Thank you for your reply. I would like to better understand your requirement. Do I understand you correctly: what you want is to quick pick another year? You suggest, that pressing a button or the current year switches the current month (or week) calendar to a matrix of year numbers to select on. Then the calendar switches to the current date, but in the selected year? Does that describe your requirement?

**Comment by JodasSenpai** [comment]
Yeah you described it perfectly. The current added feature is way to confusing for a normal costumer.

**Comment by rwbr** [comment]
OK, I see. 
Additional question: I introduced a new button. Is that a useful tool to open the dialog to choose the year? Or should tapping the date (month and year) at the top trigger that dialog? The second option is tricky, because the `Today`button is very close? Do you think, the icon button is just ok?
Next question: I will probably have users like you, that just wish to have the app behave in a very specific  way. What about a new parameter for the `NeatAndCleanCalendar` widget, that allows the user to provide the widget, that shows up on clicking the top bar button. It's the users decision them if the button appears in the top bar. It's also his decision, if a fully fledged date picker or just a year picker appears. 
I could provide some example code in the `example` project. But then I don't have to include that code in the library and maintain most of the flexibility. What do you think?

**Comment by JodasSenpai** [comment]
Personally I dont mind the extra button but I think we are all so used to design where tapping the date let you change the year that it would be confusing for a lot of people. I think it would be nice if something can be done so today and the date is clickable.

I am not sure if I understand... Your idea is to add another row(top bar) that only shows if user adds widget to it and the widget behaves the way the user implement it? Maybe an example would be nice. But anyway i think that any flexibility library has it's nice. Like with eventListBuilder.

**Comment by rwbr** [comment]
In v0.3.0+13 a new property was introduced to control a button that opens a date picker UI. 
```dart
final DatePickerType? datePickerType;
```

You can select between thee modes: 

```dart
enum DatePickerType { hidden, year, date }
```

* `hidden`: hides the button
* `year`: shows a year picker which allows just to select the year
* `date`: shows a full date picker dialog
