### ISSUE TITLE
Events added after initial load are not displayed in the monthly view

### ISSUE THREAD

**Issue by m-gug** [rwbr/flutter_neat_and_clean_calendar#84]
I am currently using version 0.4.9
I have had the following behavior since version 4.0:
I use the calendar in the expanded view.
Initially, events for the current month are loaded into the eventList. The events are displayed correctly.
If you switch to the previous month using a swipe gesture or the arrows, the events for the new month are loaded via onDateSelected and added to the eventList.
However, the new events are not displayed in the view. 
If I switch back to a version prior to 4.x, the code works again as expected.

However, this only seems to affect the expanded view. If you are in the current month and you collapse the view and then scroll back week by week until you reach the previous month, the added events are displayed correctly. However, as soon as you expand the view, the events disappear again.

It seems as if the complete view in the expanded view is not updated.

**Comment by rwbr** [comment]
Could you please add a pseudo code snippet about how your parent widget (your app) works? How does your onDateSelected-callback look like?

**Comment by rwbr** [comment]
To reproduce your problem I modified the example's `main.dart`

In **line 54** I removed the `final`keyword so that I later can assign new values to `_eventList`

```dart
List<NeatCleanCalendarEvent> _eventList = [ 
```

Additional from **line 187** on I added a new code block in the callback function of `onDateSelected`:

```dart
          onDateSelected: (value) {
            print('Date selected $value');
            List<NeatCleanCalendarEvent> newEventList = [
              NeatCleanCalendarEvent(
                'MultiDay Event A',
                description: 'test desc',
                startTime: DateTime(value.year, value.month, value.day, 10, 0),
                endTime: DateTime(value.year, value.month, value.day, 12, 0),
                color: Colors.pink,
                isMultiDay: false,
              ),
            ];
            setState(() {
              _eventList = newEventList;
            });
```

Here I set the `_eventList` to just one event in the currently selected range. 

If the calendar view is expanded and you use the arrow keys or a swipe gesture to navigate to a different month

- a new event is added to the list on the current date, but the month is set to the selected one
- example: today is the 22. August, user selects July, new event added on 22. July at 10:00 am
- event is displayed as a dot in the calendar view as well as in the calendar list
- works similar if calendar is not expanded

![Simulator Screenshot - iPhone 15 Plus - 2024-08-22 at 08 51 44](https://github.com/user-attachments/assets/3b7f0cb4-2e39-46c5-a97e-ded3e9dce923)

![Simulator Screenshot - iPhone 15 Plus - 2024-08-22 at 08 52 07](https://github.com/user-attachments/assets/d4f02c17-036b-43e4-9937-253b355d90a5)

I don't see, how I can reproduce your problem at this moment.

**Comment by m-gug** [comment]
I was able to pin down the problem.
I'm showing a LoadingIndicator while fetching the new events from the backend and that somehow messes with the rendering of the calendar.

If you take the changes you mentioned above and change the code further:

**After line 40** add:
`bool isLoading = false;`

Then right **after line 111** (Widget build(....)) add this:
```
if (isLoading) {
      return Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      );
    }
````

And then change **onDateSelected** to:
```
onDateSelected: (value) async {
            print('Date selected $value');
            setState(() {
              isLoading = true;
            });
            await Future.delayed(Duration(seconds: 2));
            List<NeatCleanCalendarEvent> newEventList = [
              NeatCleanCalendarEvent(
                'MultiDay Event A',
                description: 'test desc',
                startTime: DateTime(value.year, value.month, value.day, 10, 0),
                endTime: DateTime(value.year, value.month, value.day, 12, 0),
                color: Colors.pink,
                isMultiDay: false,
              ),
            ];
            setState(() {
              _eventList = newEventList;
            });
            setState(() {
              isLoading = false;
            });
          },
```

Now you see, that not even the month get's changed. Since we were using **initialDate** and updating that in **onDateSelected**, it was not that obvoius for me, because that way, the Month get's updated in the view, but nothing else.

I was able to work around the problem by removing the LoadingIndicator with the if and rather have it as an overlay.

**Comment by m-gug** [comment]
@rwbr At least we are one step further :-), if I can help in any way, please let me know.

**Comment by rwbr** [comment]
I'm getting closer to figuring this out. It seems that the way you're using the CircularProgressIndicator is causing Flutter to completely re-render the entire calendar widget (which is why the initState method is being called). I can't explain in detail why Flutter behaves this way, but it looks like Flutter decides to rebuild the entire calendar widget when the CircularProgressIndicator is hidden. This doesn't happen when the `await Future.delayed(Duration(seconds: 2));` call is removed, as the flow then appears to be more linear for Flutter.

This behavior leads to the initState method being called in the calendar widget. There's an issue in that method: it first updates the internal `eventsMap` and then sets the `_selectedDate`. Later, when the calendar is rendered, the `_selectedDate` points to a different month, which results in an empty view.

There are several possible solutions:

1. **Correct the initState method:** The order of operations needs to be changed.
2. **Display the CircularProgressIndicator differently:** You could show the indicator in a way that keeps the calendar visible, so Flutter doesn’t trigger a re-render.

I recommend going with option 1, and I’d like you to try out the `fix-initstate` branch for that.

**Comment by m-gug** [comment]
Hi!
Variant 1 looks good with thisbranch.
I have already converted the loading indicator into an overlay.
However, the InitialDate did not work properly even without all the dynamic loading. 
If you omit all the changes to the original demo app and simply insert `initialDate: new DateTime(2024, 7, 1),` the display was no longer correct.
However, the problem seems to have been solved by changing the sequence and the initState. My app now works as it should again
Thanks for the quick fix!
