### ISSUE TITLE
External json

### ISSUE THREAD

**Issue by tobasco** [rwbr/flutter_neat_and_clean_calendar#85]
I am looking for a way how to display events from an external json

Thanks

**Comment by rwbr** [comment]
That depends on your JSON structure. The calendar widget takes a List<NeatCleanCalendarEvent>? as parameter. So I guess you have to find a way to convert your JSON object accordingly. 
I have no plans to implement a method to set the calendar events from a JSON object, because there is no standard structure for it. It must be implemented in your app.
